const STATES = {
  GREETING: 'GREETING',
  MENU: 'MENU',
  ORDERING: 'ORDERING',
  CONFIRM: 'CONFIRM',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  PAYMENT_SENT: 'PAYMENT_SENT',
  DONE: 'DONE',
  PAUSED: 'PAUSED',
};

module.exports = { STATES };
